name: CI
on:
  push:
    branches:
      - main
      - release/*
  pull_request_target:
  merge_group:
    branches: [ main ]
jobs:
  unit:
    runs-on: ubuntu-latest
    name: Unit Tests
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Set up Go 1.21
        uses: actions/setup-go@v3
        with:
          go-version: 1.21
        id: go

      - name: Run account tests
        working-directory: src/account
        run: go test -p 1 -count=1 ./...

      - name: Run notification tests
        working-directory: src/notification
        run: go test -p 1 -count=1 ./...

      - name: Run shipment tests
        working-directory: src/shipment
        run: go test -p 1 -count=1 ./...

  contract:
    needs: [ unit ]
    runs-on: ubuntu-latest
    name: Contract Tests
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Set up Go 1.21
        uses: actions/setup-go@v3
        with:
          go-version: 1.21
        id: go

      - name: Start containers
        uses: hoverkraft-tech/compose-action@v1.5.1
        with:
          compose-file: "./test/contract/docker/docker-compose.yml"

      - name: Run contract tests
        working-directory: test/contract
        run: go test -p 1 -count=1 ./...

  integration:
    needs: [ unit, contract ]
    runs-on: ubuntu-latest
    name: Integration Tests
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Set up Go 1.21
        uses: actions/setup-go@v3
        with:
          go-version: 1.21
        id: go

      - name: Start containers
        uses: hoverkraft-tech/compose-action@v1.5.1
        with:
          compose-file: "./test/integration/docker/docker-compose.yml"

      - name: Run integration tests
        working-directory: test/integration
        run: go test -p 1 -count=1 ./...

  component:
    needs: [ unit, contract, integration ]
    runs-on: ubuntu-latest
    name: Component Tests
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Set up Go 1.21
        uses: actions/setup-go@v3
        with:
          go-version: 1.21
        id: go

      - name: Setup component test environment
        uses: hoverkraft-tech/compose-action@v1.5.1
        with:
          compose-file: "./test/component/docker/docker-compose.yml"

      - name: Run component tests
        working-directory: test/component
        run: go test -p 1 -count=1 ./...

  end2end-back:
    needs: [ unit, contract, integration, component ]
    runs-on: ubuntu-latest
    name: End2End Back Tests
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Set up Go 1.21
        uses: actions/setup-go@v3
        with:
          go-version: 1.21
        id: go

      - name: Start containers
        uses: hoverkraft-tech/compose-action@v1.5.1
        with:
          compose-file: "./test/end2end/docker/docker-compose.yml"

      - name: Run end2end tests
        working-directory: test/end2end
        run: go test -p 1 -count=1 ./...

  end2end-front:
    needs: [ unit, contract, integration, component, end2end-back ]
    runs-on: ubuntu-latest
    name: End2End Front Tests
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: npm run build
          start: npm start
          browser: chrome

      - name: Start containers
        uses: hoverkraft-tech/compose-action@v1.5.1
        with:
          compose-file: "./test/end2end/docker/docker-compose.yml"

      - name: Run end2end tests
        working-directory: frontend/if-store
        run: npm run cypress:run
