version: '3'
services:

  account-db:
    image: postgres:14.2
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5451:5432'
    volumes:
      - ./account_data/volume:/var/lib/postgresql/data

  notification-db:
    image: postgres:14.2
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5452:5432'
    volumes:
      - ./notification_data/volume:/var/lib/postgresql/data

  shipment-db:
    image: postgres:14.2
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5453:5432'
    volumes:
      - ./shipment_data/volume:/var/lib/postgresql/data

  payment-db:
    image: postgres:14.2
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5454:5432'
    volumes:
      - ./payment_data/volume:/var/lib/postgresql/data

  inventory-db:
    image: postgres:14.2
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5455:5432'
    volumes:
      - ./inventory_data/volume:/var/lib/postgresql/data

  order-db:
    image: postgres:14.2
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5456:5432'
    volumes:
      - ./order_data/volume:/var/lib/postgresql/data

  account-app:
    build:
      context: ../../src/account/
      dockerfile: Dockerfile
    image: account
    environment:
      - POSTGRES_HOST=account-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=postgres
      - POSTGRES_SLLMODE=disable
      - POSTGRES_TIMEZONE=America/Sao_Paulo
    restart: unless-stopped
    ports:
      - "9091:9091"
    depends_on:
      - account-db

  notification-app:
    build:
      context: ../../src/notification/
      dockerfile: Dockerfile
    image: notification
    environment:
      - POSTGRES_HOST=notification-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=postgres
      - POSTGRES_SLLMODE=disable
      - POSTGRES_TIMEZONE=America/Sao_Paulo
      - ACCOUNT_URL=http://account-app:9091
    restart: unless-stopped
    ports:
      - "9092:9092"
    depends_on:
      - notification-db

  shipment-app:
    build:
      context: ../../src/shipment/
      dockerfile: Dockerfile
    image: shipment
    environment:
      - POSTGRES_HOST=shipment-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=postgres
      - POSTGRES_SLLMODE=disable
      - POSTGRES_TIMEZONE=America/Sao_Paulo
    restart: unless-stopped
    ports:
      - "9093:9093"
    depends_on:
      - shipment-db

  inventory-app:
    build:
      context: ../../src/inventory/
      dockerfile: Dockerfile
    image: inventory
    environment:
      - POSTGRES_HOST=inventory-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=postgres
      - POSTGRES_SLLMODE=disable
      - POSTGRES_TIMEZONE=America/Sao_Paulo
    restart: unless-stopped
    ports:
      - "9094:9094"
    depends_on:
      - inventory-db

  order-app:
    build:
      context: ../../src/order/
      dockerfile: Dockerfile
    image: order
    environment:
      - POSTGRES_HOST=order-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=postgres
      - POSTGRES_SLLMODE=disable
      - POSTGRES_TIMEZONE=America/Sao_Paulo
      - INVENTORY_URL=http://inventory-app:9094
      - NOTIFICATION_URL=http://notification-app:9092
      - SHIPMENT_URL=http://shipment-app:9093
      - PAYMENT_URL=http://payment-app:9096
    restart: unless-stopped
    ports:
      - "9095:9095"
    depends_on:
      - order-db

  payment-app:
    build:
      context: ../../src/payment/
      dockerfile: Dockerfile
    image: payment
    environment:
      - POSTGRES_HOST=payment-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=postgres
      - POSTGRES_SLLMODE=disable
      - POSTGRES_TIMEZONE=America/Sao_Paulo
      - PORT=9096
    restart: unless-stopped
    ports:
      - "9096:9096"
    depends_on:
      - payment-db

  frontend-app:
    build:
      context: ../../frontend/if-store/
      dockerfile: Dockerfile
    image: frontend
    environment:
      - REACT_APP_INVENTORY_URL=http://localhost:9094
      - REACT_APP_ACCOUNT_URL=http://localhost:9091
      - REACT_APP_PAYMENT_URL=http://localhost:9096
      - REACT_APP_SHIPMENT_URL=http://localhost:9093
      - REACT_APP_ORDER_URL=http://localhost:9095
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - inventory-app
      - account-app
      - order-app
      - shipment-app
      - notification-app