name: CI

on:
  push:
    branches:
      - main
      - release/*
  pull_request_target:
  merge_group:
    branches: [main]

jobs:
  unit:
    runs-on: ubuntu-latest
    name: Unit Tests
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Set up Go 1.21
        uses: actions/setup-go@v5
        with:
          go-version: 1.21

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Run account tests
        working-directory: src/account
        run: |
          go mod download         
          go test -p 1 -count=1 ./...

      - name: Run notification tests
        working-directory: src/notification
        run: |
          go mod download         
          go test -p 1 -count=1 ./...

      - name: Run shipment tests
        working-directory: src/shipment
        run: |
          go mod download         
          go test -p 1 -count=1 ./...

      - name: Run payment tests
        working-directory: src/payment
        run: |
          npm ci
          npm test

  contract:
    needs: [unit]
    runs-on: ubuntu-latest
    name: Contract Tests
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Cache Go dependencies
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}-shared

      - name: Set up Go 1.21
        uses: actions/setup-go@v5
        with:
          go-version: 1.21

      - name: Start containers
        working-directory: test/contract/docker
        run: docker compose up -d

      - name: Run contract tests
        working-directory: test/contract
        run: |
          go mod download         
          go test -p 1 -count=1 ./...

      - name: Stop containers
        working-directory: test/contract/docker
        run: docker compose down

  integration:
    needs: [unit, contract]
    runs-on: ubuntu-latest
    name: Integration Tests
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Cache Go dependencies
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}-shared

      - name: Set up Go 1.21
        uses: actions/setup-go@v5
        with:
          go-version: 1.21

      - name: Start containers
        working-directory: test/integration/docker
        run: docker compose up -d

      - name: Run integration tests
        working-directory: test/integration
        run: |
          go mod download         
          go test -p 1 -count=1 ./...

      - name: Stop containers
        working-directory: test/integration/docker
        run: docker compose down

  component:
    needs: [unit, contract, integration]
    runs-on: ubuntu-latest
    name: Component Tests
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Cache Go dependencies
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}-shared

      - name: Set up Go 1.21
        uses: actions/setup-go@v5
        with:
          go-version: 1.21

      - name: Start containers
        working-directory: test/component/docker
        run: docker compose up -d

      - name: Run component tests
        working-directory: test/component
        run: |
          go mod download         
          go test -p 1 -count=1 ./...

      - name: Stop containers
        working-directory: test/component/docker
        run: docker compose down

  end2end-back:
    needs: [unit, contract, integration, component]
    runs-on: ubuntu-latest
    name: End2End Back Tests
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Cache Go dependencies
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}-shared

      - name: Set up Go 1.21
        uses: actions/setup-go@v5
        with:
          go-version: 1.21

      - name: Start containers
        working-directory: test/end2end/docker
        run: docker compose up -d

      - name: Run end2end tests
        working-directory: test/end2end
        run: |
          go mod download         
          go test -p 1 -count=1 ./...

      - name: Stop containers
        working-directory: test/end2end/docker
        run: docker compose down

  end2end-front:
    needs: [unit, contract, integration, component, end2end-back]
    runs-on: ubuntu-latest
    name: End2End Front Tests
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Start containers
        working-directory: test/end2end/docker
        run: docker compose up -d

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          build: npx cypress info
          working-directory: ./frontend/if-store

      - name: Stop containers
        working-directory: test/end2end/docker
        run: docker compose down
